version: "3.7"
# docker-compose up -d
services:
  mongo:
    image: mongo
    container_name: chatapp-mongo
    volumes:
      - mongo-data:/data/db
    restart: always
    ports:
      - 27017:27017

volumes:
  mongo-data:
